# Generated by Django 3.1.4 on 2020-12-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('B', 'Baisc'), ('I', 'Intermediate'), ('A', 'Advanced')], default='B', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cour', models.CharField(max_length=30)),
                ('regional_document', models.CharField(max_length=9)),
                ('registry_identification', models.CharField(max_length=11)),
                ('born_at', models.DateField()),
            ],
        ),
    ]
